### ISSUE TITLE
Support other template engines (handlebars, ejs...)

### ISSUE THREAD

**Issue by gchaville** [niftylettuce/preview-email#12]
I'm using [email-templates](https://email-templates.js.org/) with `hbs` and I wonder if the preview package can support something else than `pug`?

Maybe override the default render function by one passed in `options`:
```js
  options = {
    dir: os.tmpdir(),
    id: uuid.v4(),
    open: { wait: false },
    template: templateFilePath,
    renderFn: pug.renderFile,
    ...options
  };

....

  const html = await pify(options.renderFn)(
    options.template,
    Object.assign(options.locals, {
      cache: true,
      pretty: true,
      dayjs
    })
  );
```

**Comment by niftylettuce** [comment]
I would accept a PR that adds something like consolidate.  Look at my `email-templates` package and see how I made it so you can use any.

https://github.com/forwardemail/email-templates
