### ISSUE TITLE
What's the reasoning behind adding google analytics in the template?

### ISSUE THREAD

**Issue by danielberndt** [niftylettuce/preview-email#2]
I've just discovered these lines in your email template:
https://github.com/niftylettuce/preview-email/blob/337f7f1007801a2691f427856a861808f7cbab62/template.pug#L169-L172

While I understand that you might be interested in gaining insights about the usage of this package, I feel that this is somewhat inappropriate in this context.
Even in a dev environment sensitive information might be displayed.  And adding a third party script without an obvious disclaimer seems like a bad practice.

**Comment by niftylettuce** [comment]
Yeah I just had it there for insight into usage no other reason, I completely forgot it was in there too and haven't even looked at the stats haha.

Just took it out, will delete GA property on my account, and released `preview-email@0.0.7` to NPM, bump if you're using directly with `npm install preview-email@latest` or `yarn add preview-email@latest`.

Also this is a part of email-templates package, so I've also bumped this dependency there and released `email-templates@3.3.3` with this fix.  You can bump with `npm install email-templates@latest` or `yarn add email-templates@latest`.

Thanks for lmk @danielberndt, lmk of any other issues you find and thanks for using this package

**Comment by danielberndt** [comment]
Great! Thanks a lot for the prompt response :)
