### ISSUE TITLE
Allow to configure the opn command

### ISSUE THREAD

**Issue by slevy85** [niftylettuce/preview-email#4]
Hi, thank you for this great package.

I am working on Linux with visual code and recently upgraded from 1.27 to 1.28, after this upgrade the emails where not opened in the browser any more, but a window of visual code was opened.

I have found that it is because the `text/html` mime type was opened by default by visual code after the upgrade. 
Before upgrade : 
```
$ xdg-mime query default text/html
firefox.desktop
``
After upgrade : 
```
$ xdg-mime query default text/html
code-url-handler.desktop
``
I know it is not an issue with the email-preview package, but I wanted to expose the context because the xdg commands is used by `opn`.

So my need would be to have the opening command configurable so I can ask to specifically open firefox or google chrome.

Thank you very much.

**Comment by bennetstankidis** [comment]
People looking for a solution could change the default behavior of xdg for text/html. Since you probably want your browser to open html files instead of your favorite code editor.

`xdg-mime default chrome.desktop text/html` 

Note: change chrome.desktop to your browser of choice.

**Comment by slevy85** [comment]
Yes but in this case it doesn't work because vs code resets xdg-mime default after we launch it.
This bug is already reported. But if we could configure directly preview-email, we could use any software to preview the email.

**Comment by niftylettuce** [comment]
How would you like to directly configure this?  Just be able to pass a command that gets used instead of `xdg-open`?  Or?...

Related #5

**Comment by slevy85** [comment]
Maybe we could give the `opn` command a configuration object, then we can use all available configurations in `opn`. For example :
```javascript
// Specify the app to open in
opn('http://sindresorhus.com', {app: 'firefox'});
```

**Comment by niftylettuce** [comment]
Please try `email-templates@5.0.3` which uses `preview-email@0.0.10`.  I've just published both packages to NPM.  Documentation is provided at the link below which should hopefully help you resolve your OS-specific issue.  Let me know if you have any issues.

Docs: https://github.com/niftylettuce/email-templates#open-email-previews-in-firefox
