### ISSUE TITLE
Browser doesn't open in WSL

### ISSUE THREAD

**Issue by captainjapeng** [niftylettuce/preview-email#7]
I've tried several parameters for the `app` property both none worked.

Here's what I've tried:
1. `/c/Program Files (x86)/Google/Chrome/Application/chrome.exe` (Nothing happens, I have a custom mounting for docker that's why I don't have the /mnt/ prefix)
2. `explorer.exe` (Just opens a new Windows Explorer window)
3. `powershell.exe -c` (Nothing happens)
4. [wsl-open](https://raw.githubusercontent.com/4U6U57/wsl-open/master/wsl-open.sh) (Nothing happens)

**Comment by niftylettuce** [comment]
If you're directly using `preview-email`, you need to pass `open` is the option, not `app`, see https://github.com/niftylettuce/preview-email/blob/master/src/index.js#L26 and https://github.com/niftylettuce/preview-email#options

If you're using `email-templates` see https://github.com/niftylettuce/email-templates#preview and https://github.com/niftylettuce/email-templates#open-email-previews-in-firefox

If you have further issues, please see documentation for https://github.com/sindresorhus/open
